// IPodModels.swift — which iPod is plugged in.
//
// Generated from the device tables published by the libgpod project
// (https://github.com/gtkpod/libgpod, LGPL), which documents every iPod Apple
// shipped. The line is discontinued, so this table is complete and final.
//
// Copyright (C) 2026 Eddie Hajek
// Licensed under the GNU General Public License v3.0 — see the LICENSE file.

import Foundation

struct IPodModelInfo {
    let display: String   // e.g. "iPod classic (7th gen) 160 GB, Black"
    let isShuffle: Bool   // shuffles use iTunesSD, which this app doesn't write
}

private func pod(_ d: String) -> IPodModelInfo { IPodModelInfo(display: d, isShuffle: false) }
private func shuffle(_ d: String) -> IPodModelInfo { IPodModelInfo(display: d, isShuffle: true) }

/// Last three characters of the serial number → model.
let ipodSerialModels: [String: IPodModelInfo] = [
    "0JW": pod("iPod touch (1st gen) 32 GB, Silver"),
    "0KH": pod("iPhone 16 GB"),
    "1P1": pod("iPod nano (4th gen) 4 GB, Silver"),
    "1ZH": shuffle("iPod shuffle (2nd gen) 2 GB, Silver"),
    "201": pod("iPod touch (2nd gen) 8 GB, Silver"),
    "203": pod("iPod touch (2nd gen) 16 GB, Silver"),
    "2C5": pod("iPod classic (6.5 gen) 120 GB, Silver"),
    "2C7": pod("iPod classic (6.5 gen) 120 GB, Black"),
    "2ME": pod("iPod nano (4th gen) 8 GB, Silver"),
    "37H": pod("iPod nano (4th gen) 4 GB, Pink"),
    "37K": pod("iPod nano (4th gen) 4 GB, Purple"),
    "37L": pod("iPod nano (4th gen) 4 GB, Orange"),
    "37P": pod("iPod nano (4th gen) 4 GB, Green"),
    "37Q": pod("iPod nano (4th gen) 4 GB, Yellow"),
    "3NP": pod("iPhone 3GS 16 GB"),
    "3NR": pod("iPhone 3GS 32 GB"),
    "3NS": pod("iPhone 3GS 32 GB"),
    "3QS": pod("iPod nano (4th gen) 8 GB, Blue"),
    "3QT": pod("iPod nano (4th gen) 8 GB, Pink"),
    "3QU": pod("iPod nano (4th gen) 8 GB, Purple"),
    "3QW": pod("iPod nano (4th gen) 8 GB, Orange"),
    "3QX": pod("iPod nano (4th gen) 8 GB, Green"),
    "3QY": pod("iPod nano (4th gen) 8 GB, Yellow"),
    "3QZ": pod("iPod nano (4th gen) 8 GB, Red"),
    "3R0": pod("iPod nano (4th gen) 8 GB, Black"),
    "4NZ": shuffle("iPod shuffle (3rd gen) 4 GB, Silver"),
    "5B7": pod("iPod nano (4th gen) 16 GB, Silver"),
    "5B8": pod("iPod nano (4th gen) 16 GB, Blue"),
    "5B9": pod("iPod nano (4th gen) 16 GB, Pink"),
    "5BA": pod("iPod nano (4th gen) 16 GB, Purple"),
    "5BB": pod("iPod nano (4th gen) 16 GB, Orange"),
    "5BC": pod("iPod nano (4th gen) 16 GB, Green"),
    "5BD": pod("iPod nano (4th gen) 16 GB, Yellow"),
    "5BE": pod("iPod nano (4th gen) 16 GB, Red"),
    "5BF": pod("iPod nano (4th gen) 16 GB, Black"),
    "6K2": pod("iPod touch (3rd gen) 32 GB, Silver"),
    "6K4": pod("iPod touch (3rd gen) 64 GB, Silver"),
    "71V": pod("iPod nano (5th gen) 8 GB, Silver"),
    "71Y": pod("iPod nano (5th gen) 8 GB, Black"),
    "721": pod("iPod nano (5th gen) 8 GB, Purple"),
    "726": pod("iPod nano (5th gen) 8 GB, Blue"),
    "72A": pod("iPod nano (5th gen) 8 GB, Green"),
    "72F": pod("iPod nano (5th gen) 8 GB, Orange"),
    "72K": pod("iPod nano (5th gen) 8 GB, Red"),
    "72L": pod("iPod nano (5th gen) 8 GB, Pink"),
    "72Q": pod("iPod nano (5th gen) 16 GB, Silver"),
    "72R": pod("iPod nano (5th gen) 16 GB, Black"),
    "72S": pod("iPod nano (5th gen) 16 GB, Purple"),
    "72X": pod("iPod nano (5th gen) 16 GB, Blue"),
    "734": pod("iPod nano (5th gen) 16 GB, Green"),
    "738": pod("iPod nano (5th gen) 16 GB, Yellow"),
    "739": pod("iPod nano (5th gen) 16 GB, Orange"),
    "73A": pod("iPod nano (5th gen) 16 GB, Red"),
    "73B": pod("iPod nano (5th gen) 16 GB, Pink"),
    "75J": pod("iPod touch (2nd gen) 8 GB, Silver"),
    "891": shuffle("iPod shuffle (3rd gen) 4 GB, Black"),
    "8CQ": shuffle("iPod shuffle (2nd gen) 1 GB, Gold"),
    "9ZS": pod("iPod classic (7th gen) 160 GB, Silver"),
    "9ZU": pod("iPod classic (7th gen) 160 GB, Black"),
    "A1L": shuffle("iPod shuffle (3rd gen) 4 GB, Stainless"),
    "A1S": shuffle("iPod shuffle (3rd gen) 2 GB, Silver"),
    "A1U": shuffle("iPod shuffle (3rd gen) 4 GB, Green"),
    "A4S": pod("iPhone 4 16 GB"),
    "A4T": pod("iPhone 4 32 GB"),
    "A78": shuffle("iPod shuffle (3rd gen) 2 GB, Black"),
    "A7B": shuffle("iPod shuffle (3rd gen) 4 GB, Blue"),
    "A7D": shuffle("iPod shuffle (3rd gen) 4 GB, Pink"),
    "ALB": shuffle("iPod shuffle (3rd gen) 2 GB, Green"),
    "ALD": shuffle("iPod shuffle (3rd gen) 2 GB, Blue"),
    "ALG": shuffle("iPod shuffle (3rd gen) 2 GB, Pink"),
    "C60": shuffle("iPod shuffle (1st gen) 1 GB"),
    "CMJ": shuffle("iPod shuffle (4th gen) 2 GB, Silver"),
    "CMK": shuffle("iPod shuffle (4th gen) 2 GB, Pink"),
    "CMN": pod("iPod nano (6th gen) 8 GB, Silver"),
    "CMP": pod("iPod nano (6th gen) 16 GB, Silver"),
    "CP7": pod("iPod touch (4th gen) 8 GB, Silver"),
    "CP9": pod("iPod touch (4th gen) 32 GB, Silver"),
    "CPC": pod("iPod touch (4th gen) 64 GB, Silver"),
    "DVX": pod("iPod nano (6th gen) 8 GB, Black"),
    "DVY": pod("iPod nano (6th gen) 8 GB, Blue"),
    "DW0": pod("iPod nano (6th gen) 8 GB, Green"),
    "DW1": pod("iPod nano (6th gen) 8 GB, Orange"),
    "DW2": pod("iPod nano (6th gen) 8 GB, Pink"),
    "DW3": pod("iPod nano (6th gen) 8 GB, Red"),
    "DW4": pod("iPod nano (6th gen) 16 GB, Black"),
    "DW5": pod("iPod nano (6th gen) 16 GB, Blue"),
    "DW6": pod("iPod nano (6th gen) 16 GB, Green"),
    "DW7": pod("iPod nano (6th gen) 16 GB, Orange"),
    "DW8": pod("iPod nano (6th gen) 16 GB, Pink"),
    "DW9": pod("iPod nano (6th gen) 16 GB, Red"),
    "FDM": shuffle("iPod shuffle (4th gen) 2 GB, Orange"),
    "FDN": shuffle("iPod shuffle (4th gen) 2 GB, Green"),
    "FDP": shuffle("iPod shuffle (4th gen) 2 GB, Blue"),
    "LG6": pod("iPod (1st gen) 5 GB"),
    "MJ2": pod("iPod (1st gen) 5 GB"),
    "ML1": pod("iPod (1st gen) 10 GB"),
    "MMB": pod("iPod (2nd gen) 10 GB"),
    "MMC": pod("iPod (2nd gen) 20 GB"),
    "MME": pod("iPod (1st gen) 10 GB"),
    "MMF": pod("iPod (2nd gen) 20 GB"),
    "NAM": pod("iPod (1st gen) 5 GB"),
    "NGE": pod("iPod (2nd gen) 10 GB"),
    "NGH": pod("iPod (2nd gen) 10 GB"),
    "NLW": pod("iPod (3rd gen) 15 GB"),
    "NLY": pod("iPod (3rd gen) 30 GB"),
    "NM7": pod("iPod (3rd gen) 30 GB"),
    "NRH": pod("iPod (3rd gen) 10 GB"),
    "PFV": shuffle("iPod shuffle (1st gen) 500 MB"),
    "PFW": pod("iPod mini (1st gen) 4 GB"),
    "PNT": pod("iPod (3rd gen) 20 GB"),
    "PNU": pod("iPod (3rd gen) 40 GB"),
    "PQ5": pod("iPod (3rd gen) 20 GB"),
    "PQ7": pod("iPod (4th gen) 40 GB"),
    "PRC": pod("iPod mini (1st gen) 4 GB"),
    "PS9": pod("iPod (4th gen) 20 GB"),
    "Q8U": pod("iPod (4th gen) 20 GB"),
    "QGV": shuffle("iPod shuffle (1st gen) 500 MB"),
    "QKJ": pod("iPod mini (1st gen) 4 GB, Green"),
    "QKK": pod("iPod mini (1st gen) 4 GB, Pink"),
    "QKL": pod("iPod mini (1st gen) 4 GB, Blue"),
    "QKM": pod("iPod mini (1st gen) 4 GB, Gold"),
    "QKN": pod("iPod mini (1st gen) 4 GB, Green"),
    "QKP": pod("iPod mini (1st gen) 4 GB, Pink"),
    "QKQ": pod("iPod mini (1st gen) 4 GB, Blue"),
    "QKR": pod("iPod mini (1st gen) 4 GB, Gold"),
    "QQF": pod("iPod (3rd gen) 15 GB"),
    "R5Q": pod("iPod photo 40 GB"),
    "R5R": pod("iPod photo 60 GB"),
    "R5T": pod("iPod photo 60 GB"),
    "R80": shuffle("iPod shuffle (1st gen) 500 MB"),
    "RS9": shuffle("iPod shuffle (1st gen) 500 MB"),
    "RSA": shuffle("iPod shuffle (1st gen) 1 GB"),
    "S2X": pod("iPod (4th gen) 25 GB, U2 Edition"),
    "S41": pod("iPod mini (2nd gen) 4 GB"),
    "S42": pod("iPod mini (2nd gen) 6 GB"),
    "S43": pod("iPod mini (2nd gen) 4 GB, Blue"),
    "S44": pod("iPod mini (2nd gen) 6 GB, Blue"),
    "S45": pod("iPod mini (2nd gen) 4 GB, Pink"),
    "S47": pod("iPod mini (2nd gen) 4 GB, Green"),
    "S48": pod("iPod mini (2nd gen) 6 GB, Green"),
    "S4C": pod("iPod mini (2nd gen) 4 GB"),
    "S4J": pod("iPod mini (2nd gen) 4 GB, Green"),
    "SAY": pod("iPod photo 30 GB"),
    "SAZ": pod("iPod photo 60 GB"),
    "SB1": pod("iPod photo 60 GB"),
    "SZ9": pod("iPod video (5th gen) 30 GB, White"),
    "SZA": pod("iPod video (5th gen) 60 GB, White"),
    "SZB": pod("iPod nano (1st gen) 2 GB, White"),
    "SZC": pod("iPod nano (1st gen) 4 GB, White"),
    "SZT": pod("iPod nano (1st gen) 4 GB, White"),
    "SZU": pod("iPod video (5th gen) 60 GB, White"),
    "SZV": pod("iPod nano (1st gen) 2 GB, White"),
    "SZW": pod("iPod nano (1st gen) 2 GB, White"),
    "TDS": pod("iPod photo 20 GB"),
    "TDU": pod("iPod photo 20 GB"),
    "TJT": pod("iPod nano (1st gen) 2 GB, Black"),
    "TJU": pod("iPod nano (1st gen) 2 GB, Black"),
    "TK2": pod("iPod nano (1st gen) 4 GB, Black"),
    "TK3": pod("iPod nano (1st gen) 4 GB, Black"),
    "TM2": pod("iPod photo 20 GB, U2 Edition"),
    "TSX": shuffle("iPod shuffle (1st gen) 500 MB"),
    "TSY": shuffle("iPod shuffle (1st gen) 1 GB"),
    "TXK": pod("iPod video (5th gen) 30 GB, Black"),
    "TXL": pod("iPod video (5th gen) 60 GB, Black"),
    "TXM": pod("iPod video (5th gen) 30 GB, Black"),
    "TXN": pod("iPod video (5th gen) 60 GB, Black"),
    "UNA": pod("iPod nano (1st gen) 1 GB, White"),
    "UNB": pod("iPod nano (1st gen) 1 GB, White"),
    "UPR": pod("iPod nano (1st gen) 1 GB, Black"),
    "UPS": pod("iPod nano (1st gen) 1 GB, Black"),
    "V8T": pod("iPod nano (2nd gen) 4 GB, Silver"),
    "V8U": pod("iPod nano (2nd gen) 4 GB, Silver"),
    "V8W": pod("iPod nano (2nd gen) 4 GB, Blue"),
    "V8X": pod("iPod nano (2nd gen) 4 GB, Blue"),
    "V95": pod("iPod video (5.5 gen) 80 GB, Black"),
    "V96": pod("iPod video (5.5 gen) 80 GB, Black"),
    "V9K": pod("iPod video (5.5 gen) 30 GB, White"),
    "V9L": pod("iPod video (5.5 gen) 30 GB, White"),
    "V9M": pod("iPod video (5.5 gen) 30 GB, Black"),
    "V9N": pod("iPod video (5.5 gen) 30 GB, Black"),
    "V9P": pod("iPod video (5.5 gen) 80 GB, White"),
    "V9Q": pod("iPod video (5.5 gen) 80 GB, White"),
    "V9R": pod("iPod video (5.5 gen) 80 GB, Black"),
    "V9S": pod("iPod video (5.5 gen) 80 GB, Black"),
    "V9V": pod("iPod (4th gen) 25 GB, U2 Edition"),
    "VKL": pod("iPod nano (2nd gen) 4 GB, Pink"),
    "VQ5": pod("iPod nano (2nd gen) 2 GB, Silver"),
    "VQ6": pod("iPod nano (2nd gen) 2 GB, Silver"),
    "VQH": pod("iPod nano (2nd gen) 4 GB, Green"),
    "VQJ": pod("iPod nano (2nd gen) 4 GB, Green"),
    "VQK": pod("iPod nano (2nd gen) 4 GB, Pink"),
    "VQM": pod("iPod video (5.5 gen) 30 GB, Black"),
    "VQT": pod("iPod nano (2nd gen) 8 GB, Black"),
    "VQU": pod("iPod nano (2nd gen) 8 GB, Black"),
    "VR0": pod("iPhone 4 GB"),
    "VTE": shuffle("iPod shuffle (2nd gen) 1 GB, Silver"),
    "VTF": shuffle("iPod shuffle (2nd gen) 1 GB, Silver"),
    "W4N": pod("iPod touch (1st gen) 8 GB, Silver"),
    "W4T": pod("iPod touch (1st gen) 16 GB, Silver"),
    "W9G": pod("iPod video (5.5 gen) 30 GB, U2"),
    "WEC": pod("iPod video (5th gen) 30 GB, White"),
    "WED": pod("iPod video (5th gen) 30 GB, White"),
    "WEE": pod("iPod video (5.5 gen) 30 GB, Black"),
    "WEF": pod("iPod video (5th gen) 30 GB, Black"),
    "WEG": pod("iPod video (5th gen) 30 GB, White"),
    "WEH": pod("iPod video (5th gen) 30 GB, White"),
    "WEJ": pod("iPod video (5th gen) 30 GB, Black"),
    "WEK": pod("iPod video (5th gen) 30 GB, Black"),
    "WEL": pod("iPod video (5th gen) 30 GB, White"),
    "WH8": pod("iPhone 8 GB"),
    "WL2": pod("iPod nano (2nd gen) 4 GB, Red"),
    "WL3": pod("iPod nano (2nd gen) 4 GB, Red"),
    "WU9": pod("iPod video (5.5 gen) 30 GB, White"),
    "WUC": pod("iPod video (5.5 gen) 80 GB, Black"),
    "X9A": pod("iPod nano (2nd gen) 8 GB, Red"),
    "X9B": pod("iPod nano (2nd gen) 8 GB, Red"),
    "XQ5": shuffle("iPod shuffle (2nd gen) 1 GB, Pink"),
    "XQS": shuffle("iPod shuffle (2nd gen) 1 GB, Pink"),
    "XQV": shuffle("iPod shuffle (2nd gen) 1 GB, Blue"),
    "XQX": shuffle("iPod shuffle (2nd gen) 1 GB, Blue"),
    "XQY": shuffle("iPod shuffle (2nd gen) 1 GB, Green"),
    "XR1": shuffle("iPod shuffle (2nd gen) 1 GB, Orange"),
    "Y0P": pod("iPod nano (3rd gen) 4 GB, Silver"),
    "Y0R": pod("iPod nano (3rd gen) 8 GB, Silver"),
    "Y5N": pod("iPod classic (6th gen) 80 GB, Silver"),
    "Y7H": pod("iPhone 3G 8 GB"),
    "Y7K": pod("iPhone 3G 16 GB"),
    "YMU": pod("iPod classic (6th gen) 160 GB, Silver"),
    "YMV": pod("iPod classic (6th gen) 80 GB, Black"),
    "YMX": pod("iPod classic (6th gen) 160 GB, Black"),
    "YX6": shuffle("iPod shuffle (2nd gen) 1 GB, Silver"),
    "YX7": shuffle("iPod shuffle (2nd gen) 1 GB, Blue"),
    "YX8": shuffle("iPod shuffle (2nd gen) 1 GB, Green"),
    "YX9": shuffle("iPod shuffle (2nd gen) 1 GB, Silver"),
    "YXA": shuffle("iPod shuffle (2nd gen) 1 GB, Purple"),
    "YXR": pod("iPod nano (3rd gen) 8 GB, Blue"),
    "YXT": pod("iPod nano (3rd gen) 8 GB, Green"),
    "YXV": pod("iPod nano (3rd gen) 8 GB, Red"),
    "YXX": pod("iPod nano (3rd gen) 8 GB, Black"),
    "Z38": pod("iPad 16 GB"),
    "Z39": pod("iPad 32 GB"),
    "Z3A": pod("iPad 64 GB"),
]

/// Model number without its leading letter ("MC297LL/A" → "C297") → model.
let ipodNumberModels: [String: IPodModelInfo] = [
    "8513": pod("iPod (1st gen) 5 GB"),
    "8541": pod("iPod (1st gen) 5 GB"),
    "8697": pod("iPod (1st gen) 5 GB"),
    "8709": pod("iPod (1st gen) 10 GB"),
    "8737": pod("iPod (2nd gen) 10 GB"),
    "8738": pod("iPod (2nd gen) 20 GB"),
    "8740": pod("iPod (2nd gen) 10 GB"),
    "8741": pod("iPod (2nd gen) 20 GB"),
    "8946": pod("iPod (3rd gen) 15 GB"),
    "8948": pod("iPod (3rd gen) 30 GB"),
    "8976": pod("iPod (3rd gen) 10 GB"),
    "9160": pod("iPod mini (1st gen) 4 GB"),
    "9244": pod("iPod (3rd gen) 20 GB"),
    "9245": pod("iPod (3rd gen) 40 GB"),
    "9268": pod("iPod (4th gen) 40 GB"),
    "9282": pod("iPod (4th gen) 20 GB"),
    "9434": pod("iPod mini (1st gen) 4 GB, Green"),
    "9435": pod("iPod mini (1st gen) 4 GB, Pink"),
    "9436": pod("iPod mini (1st gen) 4 GB, Blue"),
    "9437": pod("iPod mini (1st gen) 4 GB, Gold"),
    "9460": pod("iPod (3rd gen) 15 GB"),
    "9585": pod("iPod photo 40 GB"),
    "9586": pod("iPod photo 60 GB"),
    "9724": shuffle("iPod shuffle (1st gen) 500 MB"),
    "9725": shuffle("iPod shuffle (1st gen) 1 GB"),
    "9787": pod("iPod (4th gen) 25 GB, U2 Edition"),
    "9800": pod("iPod mini (2nd gen) 4 GB"),
    "9801": pod("iPod mini (2nd gen) 6 GB"),
    "9802": pod("iPod mini (2nd gen) 4 GB, Blue"),
    "9803": pod("iPod mini (2nd gen) 6 GB, Blue"),
    "9804": pod("iPod mini (2nd gen) 4 GB, Pink"),
    "9805": pod("iPod mini (2nd gen) 6 GB, Pink"),
    "9806": pod("iPod mini (2nd gen) 4 GB, Green"),
    "9807": pod("iPod mini (2nd gen) 6 GB, Green"),
    "9829": pod("iPod photo 30 GB"),
    "9830": pod("iPod photo 60 GB"),
    "A002": pod("iPod video (5th gen) 30 GB, White"),
    "A003": pod("iPod video (5th gen) 60 GB, White"),
    "A004": pod("iPod nano (1st gen) 2 GB, White"),
    "A005": pod("iPod nano (1st gen) 4 GB, White"),
    "A079": pod("iPod photo 20 GB"),
    "A099": pod("iPod nano (1st gen) 2 GB, Black"),
    "A107": pod("iPod nano (1st gen) 4 GB, Black"),
    "A127": pod("iPod photo 20 GB, U2 Edition"),
    "A146": pod("iPod video (5th gen) 30 GB, Black"),
    "A147": pod("iPod video (5th gen) 60 GB, Black"),
    "A350": pod("iPod nano (1st gen) 1 GB, White"),
    "A352": pod("iPod nano (1st gen) 1 GB, Black"),
    "A426": pod("iPod nano (2nd gen) 4 GB, Silver"),
    "A428": pod("iPod nano (2nd gen) 4 GB, Blue"),
    "A444": pod("iPod video (5.5 gen) 30 GB, White"),
    "A446": pod("iPod video (5.5 gen) 30 GB, Black"),
    "A448": pod("iPod video (5.5 gen) 80 GB, White"),
    "A450": pod("iPod video (5.5 gen) 80 GB, Black"),
    "A452": pod("iPod video (5th gen) 30 GB, U2"),
    "A477": pod("iPod nano (2nd gen) 2 GB, Silver"),
    "A487": pod("iPod nano (2nd gen) 4 GB, Green"),
    "A489": pod("iPod nano (2nd gen) 4 GB, Pink"),
    "A497": pod("iPod nano (2nd gen) 8 GB, Black"),
    "A501": pod("iPhone 4 GB"),
    "A546": shuffle("iPod shuffle (2nd gen) 1 GB, Silver"),
    "A623": pod("iPod touch (1st gen) 8 GB, Silver"),
    "A627": pod("iPod touch (1st gen) 16 GB, Silver"),
    "A664": pod("iPod video (5.5 gen) 30 GB, U2"),
    "A712": pod("iPhone 8 GB"),
    "A725": pod("iPod nano (2nd gen) 4 GB, Red"),
    "A726": pod("iPod nano (2nd gen) 8 GB, Red"),
    "A947": shuffle("iPod shuffle (2nd gen) 1 GB, Pink"),
    "A949": shuffle("iPod shuffle (2nd gen) 1 GB, Blue"),
    "A951": shuffle("iPod shuffle (2nd gen) 1 GB, Green"),
    "A953": shuffle("iPod shuffle (2nd gen) 1 GB, Orange"),
    "A978": pod("iPod nano (3rd gen) 4 GB, Silver"),
    "A980": pod("iPod nano (3rd gen) 8 GB, Silver"),
    "B029": pod("iPod classic (6th gen) 80 GB, Silver"),
    "B046": pod("iPhone 3G 8 GB"),
    "B048": pod("iPhone 3G 16 GB"),
    "B145": pod("iPod classic (6th gen) 160 GB, Silver"),
    "B147": pod("iPod classic (6th gen) 80 GB, Black"),
    "B150": pod("iPod classic (6th gen) 160 GB, Black"),
    "B225": shuffle("iPod shuffle (2nd gen) 1 GB, Silver"),
    "B227": shuffle("iPod shuffle (2nd gen) 1 GB, Blue"),
    "B228": shuffle("iPod shuffle (2nd gen) 1 GB, Blue"),
    "B229": shuffle("iPod shuffle (2nd gen) 1 GB, Green"),
    "B231": shuffle("iPod shuffle (2nd gen) 1 GB, Red"),
    "B233": shuffle("iPod shuffle (2nd gen) 1 GB, Purple"),
    "B249": pod("iPod nano (3rd gen) 8 GB, Blue"),
    "B253": pod("iPod nano (3rd gen) 8 GB, Green"),
    "B257": pod("iPod nano (3rd gen) 8 GB, Red"),
    "B261": pod("iPod nano (3rd gen) 8 GB, Black"),
    "B292": pod("iPad 16 GB"),
    "B293": pod("iPad 32 GB"),
    "B294": pod("iPad 64 GB"),
    "B376": pod("iPod touch (1st gen) 32 GB, Silver"),
    "B384": pod("iPhone 16 GB"),
    "B480": pod("iPod nano (4th gen) 4 GB, Silver"),
    "B496": pod("iPhone 3G 16 GB"),
    "B500": pod("iPhone 3G 16 GB"),
    "B518": shuffle("iPod shuffle (2nd gen) 2 GB, Silver"),
    "B520": shuffle("iPod shuffle (2nd gen) 2 GB, Blue"),
    "B522": shuffle("iPod shuffle (2nd gen) 2 GB, Green"),
    "B524": shuffle("iPod shuffle (2nd gen) 2 GB, Red"),
    "B526": shuffle("iPod shuffle (2nd gen) 2 GB, Purple"),
    "B528": pod("iPod touch (2nd gen) 8 GB, Silver"),
    "B531": pod("iPod touch (2nd gen) 16 GB, Silver"),
    "B533": pod("iPod touch (2nd gen) 32 GB, Silver"),
    "B562": pod("iPod classic (6.5 gen) 120 GB, Silver"),
    "B565": pod("iPod classic (6.5 gen) 120 GB, Black"),
    "B598": pod("iPod nano (4th gen) 8 GB, Silver"),
    "B651": pod("iPod nano (4th gen) 4 GB, Blue"),
    "B654": pod("iPod nano (4th gen) 4 GB, Pink"),
    "B657": pod("iPod nano (4th gen) 4 GB, Purple"),
    "B660": pod("iPod nano (4th gen) 4 GB, Orange"),
    "B663": pod("iPod nano (4th gen) 4 GB, Green"),
    "B666": pod("iPod nano (4th gen) 4 GB, Yellow"),
    "B732": pod("iPod nano (4th gen) 8 GB, Blue"),
    "B735": pod("iPod nano (4th gen) 8 GB, Pink"),
    "B739": pod("iPod nano (4th gen) 8 GB, Purple"),
    "B742": pod("iPod nano (4th gen) 8 GB, Orange"),
    "B745": pod("iPod nano (4th gen) 8 GB, Green"),
    "B748": pod("iPod nano (4th gen) 8 GB, Yellow"),
    "B751": pod("iPod nano (4th gen) 8 GB, Red"),
    "B754": pod("iPod nano (4th gen) 8 GB, Black"),
    "B867": shuffle("iPod shuffle (3rd gen) 4 GB, Silver"),
    "B903": pod("iPod nano (4th gen) 16 GB, Silver"),
    "B905": pod("iPod nano (4th gen) 16 GB, Blue"),
    "B907": pod("iPod nano (4th gen) 16 GB, Pink"),
    "B909": pod("iPod nano (4th gen) 16 GB, Purple"),
    "B911": pod("iPod nano (4th gen) 16 GB, Orange"),
    "B913": pod("iPod nano (4th gen) 16 GB, Green"),
    "B915": pod("iPod nano (4th gen) 16 GB, Yellow"),
    "B917": pod("iPod nano (4th gen) 16 GB, Red"),
    "B918": pod("iPod nano (4th gen) 16 GB, Black"),
    "C008": pod("iPod touch (3rd gen) 32 GB, Silver"),
    "C011": pod("iPod touch (3rd gen) 64 GB, Silver"),
    "C027": pod("iPod nano (5th gen) 8 GB, Silver"),
    "C031": pod("iPod nano (5th gen) 8 GB, Black"),
    "C034": pod("iPod nano (5th gen) 8 GB, Purple"),
    "C037": pod("iPod nano (5th gen) 8 GB, Blue"),
    "C040": pod("iPod nano (5th gen) 8 GB, Green"),
    "C043": pod("iPod nano (5th gen) 8 GB, Yellow"),
    "C046": pod("iPod nano (5th gen) 8 GB, Orange"),
    "C049": pod("iPod nano (5th gen) 8 GB, Red"),
    "C050": pod("iPod nano (5th gen) 8 GB, Pink"),
    "C060": pod("iPod nano (5th gen) 16 GB, Silver"),
    "C062": pod("iPod nano (5th gen) 16 GB, Black"),
    "C064": pod("iPod nano (5th gen) 16 GB, Purple"),
    "C066": pod("iPod nano (5th gen) 16 GB, Blue"),
    "C068": pod("iPod nano (5th gen) 16 GB, Green"),
    "C070": pod("iPod nano (5th gen) 16 GB, Yellow"),
    "C072": pod("iPod nano (5th gen) 16 GB, Orange"),
    "C074": pod("iPod nano (5th gen) 16 GB, Red"),
    "C075": pod("iPod nano (5th gen) 16 GB, Pink"),
    "C086": pod("iPod touch (2nd gen) 8 GB, Silver"),
    "C131": pod("iPhone 3GS 16 GB"),
    "C133": pod("iPhone 3GS 32 GB"),
    "C134": pod("iPhone 3GS 32 GB"),
    "C164": shuffle("iPod shuffle (3rd gen) 4 GB, Black"),
    "C167": shuffle("iPod shuffle (2nd gen) 1 GB, Gold"),
    "C293": pod("iPod classic (7th gen) 160 GB, Silver"),
    "C297": pod("iPod classic (7th gen) 160 GB, Black"),
    "C303": shuffle("iPod shuffle (3rd gen) 4 GB, Stainless"),
    "C306": shuffle("iPod shuffle (3rd gen) 2 GB, Silver"),
    "C307": shuffle("iPod shuffle (3rd gen) 4 GB, Green"),
    "C323": shuffle("iPod shuffle (3rd gen) 2 GB, Black"),
    "C328": shuffle("iPod shuffle (3rd gen) 4 GB, Blue"),
    "C331": shuffle("iPod shuffle (3rd gen) 4 GB, Pink"),
    "C349": pod("iPad 16 GB"),
    "C381": shuffle("iPod shuffle (3rd gen) 2 GB, Green"),
    "C384": shuffle("iPod shuffle (3rd gen) 2 GB, Blue"),
    "C387": shuffle("iPod shuffle (3rd gen) 2 GB, Pink"),
    "C496": pod("iPad 32 GB"),
    "C497": pod("iPad 64 GB"),
    "C525": pod("iPod nano (6th gen) 8 GB, Silver"),
    "C526": pod("iPod nano (6th gen) 16 GB, Silver"),
    "C540": pod("iPod touch (4th gen) 8 GB, Silver"),
    "C544": pod("iPod touch (4th gen) 32 GB, Silver"),
    "C547": pod("iPod touch (4th gen) 64 GB, Silver"),
    "C584": shuffle("iPod shuffle (4th gen) 2 GB, Silver"),
    "C585": shuffle("iPod shuffle (4th gen) 2 GB, Pink"),
    "C603": pod("iPhone 4 16 GB"),
    "C605": pod("iPhone 4 32 GB"),
    "C688": pod("iPod nano (6th gen) 8 GB, Black"),
    "C689": pod("iPod nano (6th gen) 8 GB, Blue"),
    "C690": pod("iPod nano (6th gen) 8 GB, Green"),
    "C691": pod("iPod nano (6th gen) 8 GB, Orange"),
    "C692": pod("iPod nano (6th gen) 8 GB, Pink"),
    "C693": pod("iPod nano (6th gen) 8 GB, Red"),
    "C694": pod("iPod nano (6th gen) 16 GB, Black"),
    "C695": pod("iPod nano (6th gen) 16 GB, Blue"),
    "C696": pod("iPod nano (6th gen) 16 GB, Green"),
    "C697": pod("iPod nano (6th gen) 16 GB, Orange"),
    "C698": pod("iPod nano (6th gen) 16 GB, Pink"),
    "C699": pod("iPod nano (6th gen) 16 GB, Red"),
    "C749": shuffle("iPod shuffle (4th gen) 2 GB, Orange"),
    "C750": shuffle("iPod shuffle (4th gen) 2 GB, Green"),
    "C751": shuffle("iPod shuffle (4th gen) 2 GB, Blue"),
    "E436": pod("iPod (4th gen) 40 GB"),
    "S492": pod("iPod photo 30 GB"),
]
